SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO




CREATE PROCEDURE [etl].[Load_ods_Turnkey_Acxiom]
(
	@BatchId INT = 0,
	@Options NVARCHAR(MAX) = null
)
AS 

BEGIN
/**************************************Comments***************************************
**************************************************************************************
Mod #:  1
Name:     SSBCLOUD\dhorstman
Date:     05/26/2016
Comments: Initial creation
*************************************************************************************/

DECLARE @RunTime DATETIME = GETDATE()

DECLARE @ExecutionId uniqueidentifier = newid();
DECLARE @ProcedureName nvarchar(255) = OBJECT_SCHEMA_NAME(@@PROCID) + '.' + OBJECT_NAME(@@PROCID);
DECLARE @SrcRowCount int = ISNULL((SELECT CONVERT(varchar, COUNT(*)) FROM stg.Turnkey_Acxiom),'0');	
DECLARE @SrcDataSize NVARCHAR(255) = '0'

/*Load Options into a temp table*/
SELECT Col1 AS OptionKey, Col2 as OptionValue INTO #Options FROM [dbo].[SplitMultiColumn](@Options, '=', ';')

/*Extract Options, default values set if the option is not specified*/	
DECLARE @DisableInsert nvarchar(5) = ISNULL((SELECT OptionValue FROM #Options WHERE OptionKey = 'DisableInsert'),'false')
DECLARE @DisableUpdate nvarchar(5) = ISNULL((SELECT OptionValue FROM #Options WHERE OptionKey = 'DisableUpdate'),'false')
DECLARE @DisableDelete nvarchar(5) = ISNULL((SELECT OptionValue FROM #Options WHERE OptionKey = 'DisableDelete'),'true')


BEGIN TRY 

PRINT 'Execution Id: ' + CONVERT(NVARCHAR(100),@ExecutionId)

EXEC etl.LogEventRecordDB @Batchid, 'Info', @ProcedureName, 'Merge Load', 'Procedure Processing', 'Start', @ExecutionId
EXEC etl.LogEventRecordDB @Batchid, 'Info', @ProcedureName, 'Merge Load', 'Src Row Count', @SrcRowCount, @ExecutionId
EXEC etl.LogEventRecordDB @Batchid, 'Info', @ProcedureName, 'Merge Load', 'Src DataSize', @SrcDataSize, @ExecutionId

SELECT CAST(NULL AS BINARY(32)) ETL_DeltaHashKey
,  ETL_FileName, AbilitecID, ProspectID, FirstName, TicketingSystemAccountID, LastName, Email, OverallMatchIndicator, PersonicxClusterCode, PersonicxCluster, PrecisionLevel, AgeInTwoYearIncrements_InputIndividual, AgeInTwoYearIncrements_1stIndividual, AgeInTwoYearIncrements_2ndIndividual, Gender_InputIndividual, Gender_1stIndividual, Gender_2ndIndividual, FirstName_1stIndividual, MiddleInitial_1stIndividual, FirstName_2ndIndividual, MiddleInitial_2ndIndividual, OccupationDetail_InputIndividual, Occupation_InputIndividual, Occupation_1stIndividual, Occupation_2ndIndividual, Education_InputIndividual, Education_1stIndividual, Education_2ndIndividual, Males_18to24, Females_18to24, UnknownGender_18to24, Males_25to34, Females_25to34, UnknownGender_25to34, Males_35to44, Females_35to44, UnknownGender_35to44, Males_45to54, Females_45to54, UnknownGender_45to54, Males_55to64, Females_55to64, UnknownGender_55to64, Males_65to74, Females_65to74, UnknownGender_65to74, Males_75plus, Females_75plus, UnknownGender_75plus, MaritalStatusinHousehold, WorkingWoman, PresenceofChildren, NumberofAdults, BankCardHolder, GasDepartmentRetailCardHolder, TravelandEntertainmentCardHolder, CreditCardHolder_UnknownType, PremiumCardHolder, UpscaleCardHolder, Income_EstimatedHousehold, InfoBasePositiveMatchIndicator, NumberofSources, SuppressionMailDMA, BusinessOwner, BaseRecordVerificationDate, HomeOwnerorRenter, LengthofResidence, HomePropertyType_Detail, HomeYearBuilt_Actual, DwellingType, HomeMarketValue, ApartmentNumber, MailOrder_Buyer, MailOrder_Responder, MailOrder_Donor, Apparel_FemaleApparel_MOBs, Apparel_Jewelry_MOBs, Apparel_MaleApparel_MOBs, Apparel_PlusSizeWomensClothing_MOBs, Apparel_TeenFashion_MOBs, Apparel_UnknownType, ArtandAntique_MOBs, ArtsandCrafts_MOBs, AutoSupplies_MOBs, Beauty_MOBs, Book_MOBs, ChildrensMerchandise_MOBs, Collectible_MOBs, ComputerSoftware_MOBs, Electronic_MOBs, Equestrian_MOBs, Food_MOBs, GeneralGiftsandMerchandise_MOBs, Gift_MOBs, Health_MOBs, HomeFurnishingandDecorating_MOBs, Merchandise_HighTicketMerchandise_MOBs, Merchandise_LowTicketMerchandise_MOBs, Music_MOBs, OutdoorGardening_MOBs, OutdoorHuntingandFishing_MOBs, PetSupplies_MOBs, Sports_GolfMOBs, Sports_MOBs, Travel_MOBs, VideoDVD_MOBs, StandardRetail_MembershipWarehouse, StandardRetail_CatalogShowroomRetailBuyers, StandardRetail_MainStreetRetail, StandardRetail_HighVolumeLowEndDepartmentStoreBuyers, StandardRetail_StandardRetail, StandardSpecialty_SportingGoods, StandardSpecialty_SpecialtyApparel, StandardSpecialty_Specialty, StandardSpecialty_ComputerElectronicsBuyers, StandardSpecialty_FurnitureBuyers, StandardSpecialty_HomeOfficeSupplyPurchases, StandardSpecialty_HomeImprovement, UpscaleRetail_HighEndRetailBuyersUpscaleRetail, UpscaleSpecialty_TravelPersonalServices, Bank_FinancialServicesBanking, FinanceCompany_FinancialServicesInstallCredit, OilCompany_OilCompany, Miscellaneous_FinancialServicesInsurance, Miscellaneous_TVMailOrderPurchases, Miscellaneous_Grocery, Miscellaneous_Miscellaneous, RetailActivity_DateofLast, OnlinePurchasingIndicator, Purchase_0to3Months, Purchase_4to6Months, Purchase_7to9Months, Purchase_10to12Months, Purchase_13to18Months, Purchase_19to24Months, Purchase_24PlusMonths, RetailPurchases_MostFrequentCategory, Vehicle_NewUsedIndicator_1stVehicle, Vehicle_NewUsedIndicator_2ndVehicle, Vehicle_DominantLifestyleIndicator, TruckOwner, MotorcycleOwner, RVOwner, Vehicle_KnownOwnedNumber, Vehicle_NewCarBuyer, Age00to02_Male, Age00to02_Female, Age00to02_UnknownGender, Age03to05_Male, Age03to05_Female, Age03to05_UnknownGender, Age06to10_Male, Age06to10_Female, Age06to10_UnknownGender, Age11to15_Male, Age11to15_Female, Age11to15_UnknownGender, Age16to17_Male, Age16to17_Female, Age16to17_UnknownGender, DiscretionaryIncomeIndex, Investing_Active, SpectatorSports_AutoMotorcycleRacing, SpectatorSports_Football, SpectatorSports_Baseball, SpectatorSports_Basketball, SpectatorSports_Hockey, SpectatorSports_Soccer, SpectatorSports_Tennis, Collectibles_SportsMemorabilia, NASCAR, SportsAndLeisure_SC, NetWorth, HomeAssessedValue_Ranges, HomeSquareFootage_Actual, HouseholdAbilitecID, PersonicxDigitalCluster, PersonicxDigitalClusterCode, NetWorthGold, RaceCode, PersonID, Address1, Address2, City, State, PostalCode, Country, HomePhone, MobilePhone, AbilitecIDAppendDate, TurnkeyStandardBundleDate
INTO #SrcData
FROM (
	SELECT  ETL_FileName, AbilitecID, ProspectID, FirstName, TicketingSystemAccountID, LastName, Email, OverallMatchIndicator, PersonicxClusterCode, PersonicxCluster, PrecisionLevel, AgeInTwoYearIncrements_InputIndividual, AgeInTwoYearIncrements_1stIndividual, AgeInTwoYearIncrements_2ndIndividual, Gender_InputIndividual, Gender_1stIndividual, Gender_2ndIndividual, FirstName_1stIndividual, MiddleInitial_1stIndividual, FirstName_2ndIndividual, MiddleInitial_2ndIndividual, OccupationDetail_InputIndividual, Occupation_InputIndividual, Occupation_1stIndividual, Occupation_2ndIndividual, Education_InputIndividual, Education_1stIndividual, Education_2ndIndividual, Males_18to24, Females_18to24, UnknownGender_18to24, Males_25to34, Females_25to34, UnknownGender_25to34, Males_35to44, Females_35to44, UnknownGender_35to44, Males_45to54, Females_45to54, UnknownGender_45to54, Males_55to64, Females_55to64, UnknownGender_55to64, Males_65to74, Females_65to74, UnknownGender_65to74, Males_75plus, Females_75plus, UnknownGender_75plus, MaritalStatusinHousehold, WorkingWoman, PresenceofChildren, NumberofAdults, BankCardHolder, GasDepartmentRetailCardHolder, TravelandEntertainmentCardHolder, CreditCardHolder_UnknownType, PremiumCardHolder, UpscaleCardHolder, Income_EstimatedHousehold, InfoBasePositiveMatchIndicator, NumberofSources, SuppressionMailDMA, BusinessOwner, BaseRecordVerificationDate, HomeOwnerorRenter, LengthofResidence, HomePropertyType_Detail, HomeYearBuilt_Actual, DwellingType, HomeMarketValue, ApartmentNumber, MailOrder_Buyer, MailOrder_Responder, MailOrder_Donor, Apparel_FemaleApparel_MOBs, Apparel_Jewelry_MOBs, Apparel_MaleApparel_MOBs, Apparel_PlusSizeWomensClothing_MOBs, Apparel_TeenFashion_MOBs, Apparel_UnknownType, ArtandAntique_MOBs, ArtsandCrafts_MOBs, AutoSupplies_MOBs, Beauty_MOBs, Book_MOBs, ChildrensMerchandise_MOBs, Collectible_MOBs, ComputerSoftware_MOBs, Electronic_MOBs, Equestrian_MOBs, Food_MOBs, GeneralGiftsandMerchandise_MOBs, Gift_MOBs, Health_MOBs, HomeFurnishingandDecorating_MOBs, Merchandise_HighTicketMerchandise_MOBs, Merchandise_LowTicketMerchandise_MOBs, Music_MOBs, OutdoorGardening_MOBs, OutdoorHuntingandFishing_MOBs, PetSupplies_MOBs, Sports_GolfMOBs, Sports_MOBs, Travel_MOBs, VideoDVD_MOBs, StandardRetail_MembershipWarehouse, StandardRetail_CatalogShowroomRetailBuyers, StandardRetail_MainStreetRetail, StandardRetail_HighVolumeLowEndDepartmentStoreBuyers, StandardRetail_StandardRetail, StandardSpecialty_SportingGoods, StandardSpecialty_SpecialtyApparel, StandardSpecialty_Specialty, StandardSpecialty_ComputerElectronicsBuyers, StandardSpecialty_FurnitureBuyers, StandardSpecialty_HomeOfficeSupplyPurchases, StandardSpecialty_HomeImprovement, UpscaleRetail_HighEndRetailBuyersUpscaleRetail, UpscaleSpecialty_TravelPersonalServices, Bank_FinancialServicesBanking, FinanceCompany_FinancialServicesInstallCredit, OilCompany_OilCompany, Miscellaneous_FinancialServicesInsurance, Miscellaneous_TVMailOrderPurchases, Miscellaneous_Grocery, Miscellaneous_Miscellaneous, RetailActivity_DateofLast, OnlinePurchasingIndicator, Purchase_0to3Months, Purchase_4to6Months, Purchase_7to9Months, Purchase_10to12Months, Purchase_13to18Months, Purchase_19to24Months, Purchase_24PlusMonths, RetailPurchases_MostFrequentCategory, Vehicle_NewUsedIndicator_1stVehicle, Vehicle_NewUsedIndicator_2ndVehicle, Vehicle_DominantLifestyleIndicator, TruckOwner, MotorcycleOwner, RVOwner, Vehicle_KnownOwnedNumber, Vehicle_NewCarBuyer, Age00to02_Male, Age00to02_Female, Age00to02_UnknownGender, Age03to05_Male, Age03to05_Female, Age03to05_UnknownGender, Age06to10_Male, Age06to10_Female, Age06to10_UnknownGender, Age11to15_Male, Age11to15_Female, Age11to15_UnknownGender, Age16to17_Male, Age16to17_Female, Age16to17_UnknownGender, DiscretionaryIncomeIndex, Investing_Active, SpectatorSports_AutoMotorcycleRacing, SpectatorSports_Football, SpectatorSports_Baseball, SpectatorSports_Basketball, SpectatorSports_Hockey, SpectatorSports_Soccer, SpectatorSports_Tennis, Collectibles_SportsMemorabilia, NASCAR, SportsAndLeisure_SC, NetWorth, HomeAssessedValue_Ranges, HomeSquareFootage_Actual, HouseholdAbilitecID, PersonicxDigitalCluster, PersonicxDigitalClusterCode, NetWorthGold, RaceCode, PersonID, Address1, Address2, City, State, PostalCode, Country, HomePhone, MobilePhone, AbilitecIDAppendDate, TurnkeyStandardBundleDate
	, ROW_NUMBER() OVER(PARTITION BY AbilitecID ORDER BY ETL_ID) RowRank
	FROM stg.Turnkey_Acxiom
) a
WHERE RowRank = 1

EXEC etl.LogEventRecordDB @Batchid, 'Info', @ProcedureName, 'Merge Load', 'Src Table Setup', 'Temp Table Loaded', @ExecutionId

UPDATE #SrcData
SET ETL_DeltaHashKey = HASHBYTES('sha2_256', ISNULL(RTRIM(AbilitecID),'DBNULL_TEXT') + ISNULL(RTRIM(AbilitecIDAppendDate),'DBNULL_TEXT') + ISNULL(RTRIM(Address1),'DBNULL_TEXT') + ISNULL(RTRIM(Address2),'DBNULL_TEXT') + ISNULL(RTRIM(Age00to02_Female),'DBNULL_TEXT') + ISNULL(RTRIM(Age00to02_Male),'DBNULL_TEXT') + ISNULL(RTRIM(Age00to02_UnknownGender),'DBNULL_TEXT') + ISNULL(RTRIM(Age03to05_Female),'DBNULL_TEXT') + ISNULL(RTRIM(Age03to05_Male),'DBNULL_TEXT') + ISNULL(RTRIM(Age03to05_UnknownGender),'DBNULL_TEXT') + ISNULL(RTRIM(Age06to10_Female),'DBNULL_TEXT') + ISNULL(RTRIM(Age06to10_Male),'DBNULL_TEXT') + ISNULL(RTRIM(Age06to10_UnknownGender),'DBNULL_TEXT') + ISNULL(RTRIM(Age11to15_Female),'DBNULL_TEXT') + ISNULL(RTRIM(Age11to15_Male),'DBNULL_TEXT') + ISNULL(RTRIM(Age11to15_UnknownGender),'DBNULL_TEXT') + ISNULL(RTRIM(Age16to17_Female),'DBNULL_TEXT') + ISNULL(RTRIM(Age16to17_Male),'DBNULL_TEXT') + ISNULL(RTRIM(Age16to17_UnknownGender),'DBNULL_TEXT') + ISNULL(RTRIM(AgeInTwoYearIncrements_1stIndividual),'DBNULL_TEXT') + ISNULL(RTRIM(AgeInTwoYearIncrements_2ndIndividual),'DBNULL_TEXT') + ISNULL(RTRIM(AgeInTwoYearIncrements_InputIndividual),'DBNULL_TEXT') + ISNULL(RTRIM(ApartmentNumber),'DBNULL_TEXT') + ISNULL(RTRIM(Apparel_FemaleApparel_MOBs),'DBNULL_TEXT') + ISNULL(RTRIM(Apparel_Jewelry_MOBs),'DBNULL_TEXT') + ISNULL(RTRIM(Apparel_MaleApparel_MOBs),'DBNULL_TEXT') + ISNULL(RTRIM(Apparel_PlusSizeWomensClothing_MOBs),'DBNULL_TEXT') + ISNULL(RTRIM(Apparel_TeenFashion_MOBs),'DBNULL_TEXT') + ISNULL(RTRIM(Apparel_UnknownType),'DBNULL_TEXT') + ISNULL(RTRIM(ArtandAntique_MOBs),'DBNULL_TEXT') + ISNULL(RTRIM(ArtsandCrafts_MOBs),'DBNULL_TEXT') + ISNULL(RTRIM(AutoSupplies_MOBs),'DBNULL_TEXT') + ISNULL(RTRIM(Bank_FinancialServicesBanking),'DBNULL_TEXT') + ISNULL(RTRIM(BankCardHolder),'DBNULL_TEXT') + ISNULL(RTRIM(BaseRecordVerificationDate),'DBNULL_TEXT') + ISNULL(RTRIM(Beauty_MOBs),'DBNULL_TEXT') + ISNULL(RTRIM(Book_MOBs),'DBNULL_TEXT') + ISNULL(RTRIM(BusinessOwner),'DBNULL_TEXT') + ISNULL(RTRIM(ChildrensMerchandise_MOBs),'DBNULL_TEXT') + ISNULL(RTRIM(City),'DBNULL_TEXT') + ISNULL(RTRIM(Collectible_MOBs),'DBNULL_TEXT') + ISNULL(RTRIM(Collectibles_SportsMemorabilia),'DBNULL_TEXT') + ISNULL(RTRIM(ComputerSoftware_MOBs),'DBNULL_TEXT') + ISNULL(RTRIM(Country),'DBNULL_TEXT') + ISNULL(RTRIM(CreditCardHolder_UnknownType),'DBNULL_TEXT') + ISNULL(RTRIM(DiscretionaryIncomeIndex),'DBNULL_TEXT') + ISNULL(RTRIM(DwellingType),'DBNULL_TEXT') + ISNULL(RTRIM(Education_1stIndividual),'DBNULL_TEXT') + ISNULL(RTRIM(Education_2ndIndividual),'DBNULL_TEXT') + ISNULL(RTRIM(Education_InputIndividual),'DBNULL_TEXT') + ISNULL(RTRIM(Electronic_MOBs),'DBNULL_TEXT') + ISNULL(RTRIM(Email),'DBNULL_TEXT') + ISNULL(RTRIM(Equestrian_MOBs),'DBNULL_TEXT') + ISNULL(RTRIM(Females_18to24),'DBNULL_TEXT') + ISNULL(RTRIM(Females_25to34),'DBNULL_TEXT') + ISNULL(RTRIM(Females_35to44),'DBNULL_TEXT') + ISNULL(RTRIM(Females_45to54),'DBNULL_TEXT') + ISNULL(RTRIM(Females_55to64),'DBNULL_TEXT') + ISNULL(RTRIM(Females_65to74),'DBNULL_TEXT') + ISNULL(RTRIM(Females_75plus),'DBNULL_TEXT') + ISNULL(RTRIM(FinanceCompany_FinancialServicesInstallCredit),'DBNULL_TEXT') + ISNULL(RTRIM(FirstName),'DBNULL_TEXT') + ISNULL(RTRIM(FirstName_1stIndividual),'DBNULL_TEXT') + ISNULL(RTRIM(FirstName_2ndIndividual),'DBNULL_TEXT') + ISNULL(RTRIM(Food_MOBs),'DBNULL_TEXT') + ISNULL(RTRIM(GasDepartmentRetailCardHolder),'DBNULL_TEXT') + ISNULL(RTRIM(Gender_1stIndividual),'DBNULL_TEXT') + ISNULL(RTRIM(Gender_2ndIndividual),'DBNULL_TEXT') + ISNULL(RTRIM(Gender_InputIndividual),'DBNULL_TEXT') + ISNULL(RTRIM(GeneralGiftsandMerchandise_MOBs),'DBNULL_TEXT') + ISNULL(RTRIM(Gift_MOBs),'DBNULL_TEXT') + ISNULL(RTRIM(Health_MOBs),'DBNULL_TEXT') + ISNULL(RTRIM(HomeAssessedValue_Ranges),'DBNULL_TEXT') + ISNULL(RTRIM(HomeFurnishingandDecorating_MOBs),'DBNULL_TEXT') + ISNULL(RTRIM(HomeMarketValue),'DBNULL_TEXT') + ISNULL(RTRIM(HomeOwnerorRenter),'DBNULL_TEXT') + ISNULL(RTRIM(HomePhone),'DBNULL_TEXT') + ISNULL(RTRIM(HomePropertyType_Detail),'DBNULL_TEXT') + ISNULL(RTRIM(HomeSquareFootage_Actual),'DBNULL_TEXT') + ISNULL(RTRIM(HomeYearBuilt_Actual),'DBNULL_TEXT') + ISNULL(RTRIM(HouseholdAbilitecID),'DBNULL_TEXT') + ISNULL(RTRIM(Income_EstimatedHousehold),'DBNULL_TEXT') + ISNULL(RTRIM(InfoBasePositiveMatchIndicator),'DBNULL_TEXT') + ISNULL(RTRIM(Investing_Active),'DBNULL_TEXT') + ISNULL(RTRIM(LastName),'DBNULL_TEXT') + ISNULL(RTRIM(LengthofResidence),'DBNULL_TEXT') + ISNULL(RTRIM(MailOrder_Buyer),'DBNULL_TEXT') + ISNULL(RTRIM(MailOrder_Donor),'DBNULL_TEXT') + ISNULL(RTRIM(MailOrder_Responder),'DBNULL_TEXT') + ISNULL(RTRIM(Males_18to24),'DBNULL_TEXT') + ISNULL(RTRIM(Males_25to34),'DBNULL_TEXT') + ISNULL(RTRIM(Males_35to44),'DBNULL_TEXT') + ISNULL(RTRIM(Males_45to54),'DBNULL_TEXT') + ISNULL(RTRIM(Males_55to64),'DBNULL_TEXT') + ISNULL(RTRIM(Males_65to74),'DBNULL_TEXT') + ISNULL(RTRIM(Males_75plus),'DBNULL_TEXT') + ISNULL(RTRIM(MaritalStatusinHousehold),'DBNULL_TEXT') + ISNULL(RTRIM(Merchandise_HighTicketMerchandise_MOBs),'DBNULL_TEXT') + ISNULL(RTRIM(Merchandise_LowTicketMerchandise_MOBs),'DBNULL_TEXT') + ISNULL(RTRIM(MiddleInitial_1stIndividual),'DBNULL_TEXT') + ISNULL(RTRIM(MiddleInitial_2ndIndividual),'DBNULL_TEXT') + ISNULL(RTRIM(Miscellaneous_FinancialServicesInsurance),'DBNULL_TEXT') + ISNULL(RTRIM(Miscellaneous_Grocery),'DBNULL_TEXT') + ISNULL(RTRIM(Miscellaneous_Miscellaneous),'DBNULL_TEXT') + ISNULL(RTRIM(Miscellaneous_TVMailOrderPurchases),'DBNULL_TEXT') + ISNULL(RTRIM(MobilePhone),'DBNULL_TEXT') + ISNULL(RTRIM(MotorcycleOwner),'DBNULL_TEXT') + ISNULL(RTRIM(Music_MOBs),'DBNULL_TEXT') + ISNULL(RTRIM(NASCAR),'DBNULL_TEXT') + ISNULL(RTRIM(NetWorth),'DBNULL_TEXT') + ISNULL(RTRIM(NetWorthGold),'DBNULL_TEXT') + ISNULL(RTRIM(NumberofAdults),'DBNULL_TEXT') + ISNULL(RTRIM(NumberofSources),'DBNULL_TEXT') + ISNULL(RTRIM(Occupation_1stIndividual),'DBNULL_TEXT') + ISNULL(RTRIM(Occupation_2ndIndividual),'DBNULL_TEXT') + ISNULL(RTRIM(Occupation_InputIndividual),'DBNULL_TEXT') + ISNULL(RTRIM(OccupationDetail_InputIndividual),'DBNULL_TEXT') + ISNULL(RTRIM(OilCompany_OilCompany),'DBNULL_TEXT') + ISNULL(RTRIM(OnlinePurchasingIndicator),'DBNULL_TEXT') + ISNULL(RTRIM(OutdoorGardening_MOBs),'DBNULL_TEXT') + ISNULL(RTRIM(OutdoorHuntingandFishing_MOBs),'DBNULL_TEXT') + ISNULL(RTRIM(OverallMatchIndicator),'DBNULL_TEXT') + ISNULL(RTRIM(PersonicxCluster),'DBNULL_TEXT') + ISNULL(RTRIM(PersonicxClusterCode),'DBNULL_TEXT') + ISNULL(RTRIM(PersonicxDigitalCluster),'DBNULL_TEXT') + ISNULL(RTRIM(PersonicxDigitalClusterCode),'DBNULL_TEXT') + ISNULL(RTRIM(PersonID),'DBNULL_TEXT') + ISNULL(RTRIM(PetSupplies_MOBs),'DBNULL_TEXT') + ISNULL(RTRIM(PostalCode),'DBNULL_TEXT') + ISNULL(RTRIM(PrecisionLevel),'DBNULL_TEXT') + ISNULL(RTRIM(PremiumCardHolder),'DBNULL_TEXT') + ISNULL(RTRIM(PresenceofChildren),'DBNULL_TEXT') + ISNULL(RTRIM(ProspectID),'DBNULL_TEXT') + ISNULL(RTRIM(Purchase_0to3Months),'DBNULL_TEXT') + ISNULL(RTRIM(Purchase_10to12Months),'DBNULL_TEXT') + ISNULL(RTRIM(Purchase_13to18Months),'DBNULL_TEXT') + ISNULL(RTRIM(Purchase_19to24Months),'DBNULL_TEXT') + ISNULL(RTRIM(Purchase_24PlusMonths),'DBNULL_TEXT') + ISNULL(RTRIM(Purchase_4to6Months),'DBNULL_TEXT') + ISNULL(RTRIM(Purchase_7to9Months),'DBNULL_TEXT') + ISNULL(RTRIM(RaceCode),'DBNULL_TEXT') + ISNULL(RTRIM(RetailActivity_DateofLast),'DBNULL_TEXT') + ISNULL(RTRIM(RetailPurchases_MostFrequentCategory),'DBNULL_TEXT') + ISNULL(RTRIM(RVOwner),'DBNULL_TEXT') + ISNULL(RTRIM(SpectatorSports_AutoMotorcycleRacing),'DBNULL_TEXT') + ISNULL(RTRIM(SpectatorSports_Baseball),'DBNULL_TEXT') + ISNULL(RTRIM(SpectatorSports_Basketball),'DBNULL_TEXT') + ISNULL(RTRIM(SpectatorSports_Football),'DBNULL_TEXT') + ISNULL(RTRIM(SpectatorSports_Hockey),'DBNULL_TEXT') + ISNULL(RTRIM(SpectatorSports_Soccer),'DBNULL_TEXT') + ISNULL(RTRIM(SpectatorSports_Tennis),'DBNULL_TEXT') + ISNULL(RTRIM(Sports_GolfMOBs),'DBNULL_TEXT') + ISNULL(RTRIM(Sports_MOBs),'DBNULL_TEXT') + ISNULL(RTRIM(SportsAndLeisure_SC),'DBNULL_TEXT') + ISNULL(RTRIM(StandardRetail_CatalogShowroomRetailBuyers),'DBNULL_TEXT') + ISNULL(RTRIM(StandardRetail_HighVolumeLowEndDepartmentStoreBuyers),'DBNULL_TEXT') + ISNULL(RTRIM(StandardRetail_MainStreetRetail),'DBNULL_TEXT') + ISNULL(RTRIM(StandardRetail_MembershipWarehouse),'DBNULL_TEXT') + ISNULL(RTRIM(StandardRetail_StandardRetail),'DBNULL_TEXT') + ISNULL(RTRIM(StandardSpecialty_ComputerElectronicsBuyers),'DBNULL_TEXT') + ISNULL(RTRIM(StandardSpecialty_FurnitureBuyers),'DBNULL_TEXT') + ISNULL(RTRIM(StandardSpecialty_HomeImprovement),'DBNULL_TEXT') + ISNULL(RTRIM(StandardSpecialty_HomeOfficeSupplyPurchases),'DBNULL_TEXT') + ISNULL(RTRIM(StandardSpecialty_Specialty),'DBNULL_TEXT') + ISNULL(RTRIM(StandardSpecialty_SpecialtyApparel),'DBNULL_TEXT') + ISNULL(RTRIM(StandardSpecialty_SportingGoods),'DBNULL_TEXT') + ISNULL(RTRIM(State),'DBNULL_TEXT') + ISNULL(RTRIM(SuppressionMailDMA),'DBNULL_TEXT') + ISNULL(RTRIM(TicketingSystemAccountID),'DBNULL_TEXT') + ISNULL(RTRIM(Travel_MOBs),'DBNULL_TEXT') + ISNULL(RTRIM(TravelandEntertainmentCardHolder),'DBNULL_TEXT') + ISNULL(RTRIM(TruckOwner),'DBNULL_TEXT') + ISNULL(RTRIM(TurnkeyStandardBundleDate),'DBNULL_TEXT') + ISNULL(RTRIM(UnknownGender_18to24),'DBNULL_TEXT') + ISNULL(RTRIM(UnknownGender_25to34),'DBNULL_TEXT') + ISNULL(RTRIM(UnknownGender_35to44),'DBNULL_TEXT') + ISNULL(RTRIM(UnknownGender_45to54),'DBNULL_TEXT') + ISNULL(RTRIM(UnknownGender_55to64),'DBNULL_TEXT') + ISNULL(RTRIM(UnknownGender_65to74),'DBNULL_TEXT') + ISNULL(RTRIM(UnknownGender_75plus),'DBNULL_TEXT') + ISNULL(RTRIM(UpscaleCardHolder),'DBNULL_TEXT') + ISNULL(RTRIM(UpscaleRetail_HighEndRetailBuyersUpscaleRetail),'DBNULL_TEXT') + ISNULL(RTRIM(UpscaleSpecialty_TravelPersonalServices),'DBNULL_TEXT') + ISNULL(RTRIM(Vehicle_DominantLifestyleIndicator),'DBNULL_TEXT') + ISNULL(RTRIM(Vehicle_KnownOwnedNumber),'DBNULL_TEXT') + ISNULL(RTRIM(Vehicle_NewCarBuyer),'DBNULL_TEXT') + ISNULL(RTRIM(Vehicle_NewUsedIndicator_1stVehicle),'DBNULL_TEXT') + ISNULL(RTRIM(Vehicle_NewUsedIndicator_2ndVehicle),'DBNULL_TEXT') + ISNULL(RTRIM(VideoDVD_MOBs),'DBNULL_TEXT') + ISNULL(RTRIM(WorkingWoman),'DBNULL_TEXT'))

EXEC etl.LogEventRecordDB @Batchid, 'Info', @ProcedureName, 'Merge Load', 'Src Table Setup', 'ETL_DeltaHashKey Set', @ExecutionId

CREATE NONCLUSTERED INDEX IDX_Load_Key ON #SrcData (AbilitecID)
CREATE NONCLUSTERED INDEX IDX_ETL_DeltaHashKey ON #SrcData (ETL_DeltaHashKey)

EXEC etl.LogEventRecordDB @Batchid, 'Info', @ProcedureName, 'Merge Load', 'Src Table Setup', 'Temp Table Indexes Created', @ExecutionId

EXEC etl.LogEventRecordDB @Batchid, 'Info', @ProcedureName, 'Merge Load', 'Merge Statement Execution', 'Start', @ExecutionId

MERGE ods.Turnkey_Acxiom AS myTarget
USING #SrcData AS mySource
ON myTarget.AbilitecID = mySource.AbilitecID

WHEN MATCHED AND (
     ISNULL(mySource.ETL_DeltaHashKey,-1) <> ISNULL(myTarget.ETL_DeltaHashKey, -1)
)
THEN UPDATE SET
       myTarget.[ETL_UpdatedDate] = @RunTime
     , myTarget.[ETL_IsDeleted] = 0
     , myTarget.[ETL_DeletedDate] = NULL
     , myTarget.[ETL_DeltaHashKey] = mySource.[ETL_DeltaHashKey]
	 , myTarget.[ETL_FileName] = mySource.[ETL_FileName]
     , myTarget.[ProspectID] = mySource.[ProspectID]
     , myTarget.[FirstName] = mySource.[FirstName]
     , myTarget.[TicketingSystemAccountID] = mySource.[TicketingSystemAccountID]
     , myTarget.[LastName] = mySource.[LastName]
     , myTarget.[Email] = mySource.[Email]
     , myTarget.[OverallMatchIndicator] = mySource.[OverallMatchIndicator]
     , myTarget.[PersonicxClusterCode] = mySource.[PersonicxClusterCode]
     , myTarget.[PersonicxCluster] = mySource.[PersonicxCluster]
     , myTarget.[PrecisionLevel] = mySource.[PrecisionLevel]
     , myTarget.[AgeInTwoYearIncrements_InputIndividual] = mySource.[AgeInTwoYearIncrements_InputIndividual]
     , myTarget.[AgeInTwoYearIncrements_1stIndividual] = mySource.[AgeInTwoYearIncrements_1stIndividual]
     , myTarget.[AgeInTwoYearIncrements_2ndIndividual] = mySource.[AgeInTwoYearIncrements_2ndIndividual]
     , myTarget.[Gender_InputIndividual] = mySource.[Gender_InputIndividual]
     , myTarget.[Gender_1stIndividual] = mySource.[Gender_1stIndividual]
     , myTarget.[Gender_2ndIndividual] = mySource.[Gender_2ndIndividual]
     , myTarget.[FirstName_1stIndividual] = mySource.[FirstName_1stIndividual]
     , myTarget.[MiddleInitial_1stIndividual] = mySource.[MiddleInitial_1stIndividual]
     , myTarget.[FirstName_2ndIndividual] = mySource.[FirstName_2ndIndividual]
     , myTarget.[MiddleInitial_2ndIndividual] = mySource.[MiddleInitial_2ndIndividual]
     , myTarget.[OccupationDetail_InputIndividual] = mySource.[OccupationDetail_InputIndividual]
     , myTarget.[Occupation_InputIndividual] = mySource.[Occupation_InputIndividual]
     , myTarget.[Occupation_1stIndividual] = mySource.[Occupation_1stIndividual]
     , myTarget.[Occupation_2ndIndividual] = mySource.[Occupation_2ndIndividual]
     , myTarget.[Education_InputIndividual] = mySource.[Education_InputIndividual]
     , myTarget.[Education_1stIndividual] = mySource.[Education_1stIndividual]
     , myTarget.[Education_2ndIndividual] = mySource.[Education_2ndIndividual]
     , myTarget.[Males_18to24] = mySource.[Males_18to24]
     , myTarget.[Females_18to24] = mySource.[Females_18to24]
     , myTarget.[UnknownGender_18to24] = mySource.[UnknownGender_18to24]
     , myTarget.[Males_25to34] = mySource.[Males_25to34]
     , myTarget.[Females_25to34] = mySource.[Females_25to34]
     , myTarget.[UnknownGender_25to34] = mySource.[UnknownGender_25to34]
     , myTarget.[Males_35to44] = mySource.[Males_35to44]
     , myTarget.[Females_35to44] = mySource.[Females_35to44]
     , myTarget.[UnknownGender_35to44] = mySource.[UnknownGender_35to44]
     , myTarget.[Males_45to54] = mySource.[Males_45to54]
     , myTarget.[Females_45to54] = mySource.[Females_45to54]
     , myTarget.[UnknownGender_45to54] = mySource.[UnknownGender_45to54]
     , myTarget.[Males_55to64] = mySource.[Males_55to64]
     , myTarget.[Females_55to64] = mySource.[Females_55to64]
     , myTarget.[UnknownGender_55to64] = mySource.[UnknownGender_55to64]
     , myTarget.[Males_65to74] = mySource.[Males_65to74]
     , myTarget.[Females_65to74] = mySource.[Females_65to74]
     , myTarget.[UnknownGender_65to74] = mySource.[UnknownGender_65to74]
     , myTarget.[Males_75plus] = mySource.[Males_75plus]
     , myTarget.[Females_75plus] = mySource.[Females_75plus]
     , myTarget.[UnknownGender_75plus] = mySource.[UnknownGender_75plus]
     , myTarget.[MaritalStatusinHousehold] = mySource.[MaritalStatusinHousehold]
     , myTarget.[WorkingWoman] = mySource.[WorkingWoman]
     , myTarget.[PresenceofChildren] = mySource.[PresenceofChildren]
     , myTarget.[NumberofAdults] = mySource.[NumberofAdults]
     , myTarget.[BankCardHolder] = mySource.[BankCardHolder]
     , myTarget.[GasDepartmentRetailCardHolder] = mySource.[GasDepartmentRetailCardHolder]
     , myTarget.[TravelandEntertainmentCardHolder] = mySource.[TravelandEntertainmentCardHolder]
     , myTarget.[CreditCardHolder_UnknownType] = mySource.[CreditCardHolder_UnknownType]
     , myTarget.[PremiumCardHolder] = mySource.[PremiumCardHolder]
     , myTarget.[UpscaleCardHolder] = mySource.[UpscaleCardHolder]
     , myTarget.[Income_EstimatedHousehold] = mySource.[Income_EstimatedHousehold]
     , myTarget.[InfoBasePositiveMatchIndicator] = mySource.[InfoBasePositiveMatchIndicator]
     , myTarget.[NumberofSources] = mySource.[NumberofSources]
     , myTarget.[SuppressionMailDMA] = mySource.[SuppressionMailDMA]
     , myTarget.[BusinessOwner] = mySource.[BusinessOwner]
     , myTarget.[BaseRecordVerificationDate] = mySource.[BaseRecordVerificationDate]
     , myTarget.[HomeOwnerorRenter] = mySource.[HomeOwnerorRenter]
     , myTarget.[LengthofResidence] = mySource.[LengthofResidence]
     , myTarget.[HomePropertyType_Detail] = mySource.[HomePropertyType_Detail]
     , myTarget.[HomeYearBuilt_Actual] = mySource.[HomeYearBuilt_Actual]
     , myTarget.[DwellingType] = mySource.[DwellingType]
     , myTarget.[HomeMarketValue] = mySource.[HomeMarketValue]
     , myTarget.[ApartmentNumber] = mySource.[ApartmentNumber]
     , myTarget.[MailOrder_Buyer] = mySource.[MailOrder_Buyer]
     , myTarget.[MailOrder_Responder] = mySource.[MailOrder_Responder]
     , myTarget.[MailOrder_Donor] = mySource.[MailOrder_Donor]
     , myTarget.[Apparel_FemaleApparel_MOBs] = mySource.[Apparel_FemaleApparel_MOBs]
     , myTarget.[Apparel_Jewelry_MOBs] = mySource.[Apparel_Jewelry_MOBs]
     , myTarget.[Apparel_MaleApparel_MOBs] = mySource.[Apparel_MaleApparel_MOBs]
     , myTarget.[Apparel_PlusSizeWomensClothing_MOBs] = mySource.[Apparel_PlusSizeWomensClothing_MOBs]
     , myTarget.[Apparel_TeenFashion_MOBs] = mySource.[Apparel_TeenFashion_MOBs]
     , myTarget.[Apparel_UnknownType] = mySource.[Apparel_UnknownType]
     , myTarget.[ArtandAntique_MOBs] = mySource.[ArtandAntique_MOBs]
     , myTarget.[ArtsandCrafts_MOBs] = mySource.[ArtsandCrafts_MOBs]
     , myTarget.[AutoSupplies_MOBs] = mySource.[AutoSupplies_MOBs]
     , myTarget.[Beauty_MOBs] = mySource.[Beauty_MOBs]
     , myTarget.[Book_MOBs] = mySource.[Book_MOBs]
     , myTarget.[ChildrensMerchandise_MOBs] = mySource.[ChildrensMerchandise_MOBs]
     , myTarget.[Collectible_MOBs] = mySource.[Collectible_MOBs]
     , myTarget.[ComputerSoftware_MOBs] = mySource.[ComputerSoftware_MOBs]
     , myTarget.[Electronic_MOBs] = mySource.[Electronic_MOBs]
     , myTarget.[Equestrian_MOBs] = mySource.[Equestrian_MOBs]
     , myTarget.[Food_MOBs] = mySource.[Food_MOBs]
     , myTarget.[GeneralGiftsandMerchandise_MOBs] = mySource.[GeneralGiftsandMerchandise_MOBs]
     , myTarget.[Gift_MOBs] = mySource.[Gift_MOBs]
     , myTarget.[Health_MOBs] = mySource.[Health_MOBs]
     , myTarget.[HomeFurnishingandDecorating_MOBs] = mySource.[HomeFurnishingandDecorating_MOBs]
     , myTarget.[Merchandise_HighTicketMerchandise_MOBs] = mySource.[Merchandise_HighTicketMerchandise_MOBs]
     , myTarget.[Merchandise_LowTicketMerchandise_MOBs] = mySource.[Merchandise_LowTicketMerchandise_MOBs]
     , myTarget.[Music_MOBs] = mySource.[Music_MOBs]
     , myTarget.[OutdoorGardening_MOBs] = mySource.[OutdoorGardening_MOBs]
     , myTarget.[OutdoorHuntingandFishing_MOBs] = mySource.[OutdoorHuntingandFishing_MOBs]
     , myTarget.[PetSupplies_MOBs] = mySource.[PetSupplies_MOBs]
     , myTarget.[Sports_GolfMOBs] = mySource.[Sports_GolfMOBs]
     , myTarget.[Sports_MOBs] = mySource.[Sports_MOBs]
     , myTarget.[Travel_MOBs] = mySource.[Travel_MOBs]
     , myTarget.[VideoDVD_MOBs] = mySource.[VideoDVD_MOBs]
     , myTarget.[StandardRetail_MembershipWarehouse] = mySource.[StandardRetail_MembershipWarehouse]
     , myTarget.[StandardRetail_CatalogShowroomRetailBuyers] = mySource.[StandardRetail_CatalogShowroomRetailBuyers]
     , myTarget.[StandardRetail_MainStreetRetail] = mySource.[StandardRetail_MainStreetRetail]
     , myTarget.[StandardRetail_HighVolumeLowEndDepartmentStoreBuyers] = mySource.[StandardRetail_HighVolumeLowEndDepartmentStoreBuyers]
     , myTarget.[StandardRetail_StandardRetail] = mySource.[StandardRetail_StandardRetail]
     , myTarget.[StandardSpecialty_SportingGoods] = mySource.[StandardSpecialty_SportingGoods]
     , myTarget.[StandardSpecialty_SpecialtyApparel] = mySource.[StandardSpecialty_SpecialtyApparel]
     , myTarget.[StandardSpecialty_Specialty] = mySource.[StandardSpecialty_Specialty]
     , myTarget.[StandardSpecialty_ComputerElectronicsBuyers] = mySource.[StandardSpecialty_ComputerElectronicsBuyers]
     , myTarget.[StandardSpecialty_FurnitureBuyers] = mySource.[StandardSpecialty_FurnitureBuyers]
     , myTarget.[StandardSpecialty_HomeOfficeSupplyPurchases] = mySource.[StandardSpecialty_HomeOfficeSupplyPurchases]
     , myTarget.[StandardSpecialty_HomeImprovement] = mySource.[StandardSpecialty_HomeImprovement]
     , myTarget.[UpscaleRetail_HighEndRetailBuyersUpscaleRetail] = mySource.[UpscaleRetail_HighEndRetailBuyersUpscaleRetail]
     , myTarget.[UpscaleSpecialty_TravelPersonalServices] = mySource.[UpscaleSpecialty_TravelPersonalServices]
     , myTarget.[Bank_FinancialServicesBanking] = mySource.[Bank_FinancialServicesBanking]
     , myTarget.[FinanceCompany_FinancialServicesInstallCredit] = mySource.[FinanceCompany_FinancialServicesInstallCredit]
     , myTarget.[OilCompany_OilCompany] = mySource.[OilCompany_OilCompany]
     , myTarget.[Miscellaneous_FinancialServicesInsurance] = mySource.[Miscellaneous_FinancialServicesInsurance]
     , myTarget.[Miscellaneous_TVMailOrderPurchases] = mySource.[Miscellaneous_TVMailOrderPurchases]
     , myTarget.[Miscellaneous_Grocery] = mySource.[Miscellaneous_Grocery]
     , myTarget.[Miscellaneous_Miscellaneous] = mySource.[Miscellaneous_Miscellaneous]
     , myTarget.[RetailActivity_DateofLast] = mySource.[RetailActivity_DateofLast]
     , myTarget.[OnlinePurchasingIndicator] = mySource.[OnlinePurchasingIndicator]
     , myTarget.[Purchase_0to3Months] = mySource.[Purchase_0to3Months]
     , myTarget.[Purchase_4to6Months] = mySource.[Purchase_4to6Months]
     , myTarget.[Purchase_7to9Months] = mySource.[Purchase_7to9Months]
     , myTarget.[Purchase_10to12Months] = mySource.[Purchase_10to12Months]
     , myTarget.[Purchase_13to18Months] = mySource.[Purchase_13to18Months]
     , myTarget.[Purchase_19to24Months] = mySource.[Purchase_19to24Months]
     , myTarget.[Purchase_24PlusMonths] = mySource.[Purchase_24PlusMonths]
     , myTarget.[RetailPurchases_MostFrequentCategory] = mySource.[RetailPurchases_MostFrequentCategory]
     , myTarget.[Vehicle_NewUsedIndicator_1stVehicle] = mySource.[Vehicle_NewUsedIndicator_1stVehicle]
     , myTarget.[Vehicle_NewUsedIndicator_2ndVehicle] = mySource.[Vehicle_NewUsedIndicator_2ndVehicle]
     , myTarget.[Vehicle_DominantLifestyleIndicator] = mySource.[Vehicle_DominantLifestyleIndicator]
     , myTarget.[TruckOwner] = mySource.[TruckOwner]
     , myTarget.[MotorcycleOwner] = mySource.[MotorcycleOwner]
     , myTarget.[RVOwner] = mySource.[RVOwner]
     , myTarget.[Vehicle_KnownOwnedNumber] = mySource.[Vehicle_KnownOwnedNumber]
     , myTarget.[Vehicle_NewCarBuyer] = mySource.[Vehicle_NewCarBuyer]
     , myTarget.[Age00to02_Male] = mySource.[Age00to02_Male]
     , myTarget.[Age00to02_Female] = mySource.[Age00to02_Female]
     , myTarget.[Age00to02_UnknownGender] = mySource.[Age00to02_UnknownGender]
     , myTarget.[Age03to05_Male] = mySource.[Age03to05_Male]
     , myTarget.[Age03to05_Female] = mySource.[Age03to05_Female]
     , myTarget.[Age03to05_UnknownGender] = mySource.[Age03to05_UnknownGender]
     , myTarget.[Age06to10_Male] = mySource.[Age06to10_Male]
     , myTarget.[Age06to10_Female] = mySource.[Age06to10_Female]
     , myTarget.[Age06to10_UnknownGender] = mySource.[Age06to10_UnknownGender]
     , myTarget.[Age11to15_Male] = mySource.[Age11to15_Male]
     , myTarget.[Age11to15_Female] = mySource.[Age11to15_Female]
     , myTarget.[Age11to15_UnknownGender] = mySource.[Age11to15_UnknownGender]
     , myTarget.[Age16to17_Male] = mySource.[Age16to17_Male]
     , myTarget.[Age16to17_Female] = mySource.[Age16to17_Female]
     , myTarget.[Age16to17_UnknownGender] = mySource.[Age16to17_UnknownGender]
     , myTarget.[DiscretionaryIncomeIndex] = mySource.[DiscretionaryIncomeIndex]
     , myTarget.[Investing_Active] = mySource.[Investing_Active]
     , myTarget.[SpectatorSports_AutoMotorcycleRacing] = mySource.[SpectatorSports_AutoMotorcycleRacing]
     , myTarget.[SpectatorSports_Football] = mySource.[SpectatorSports_Football]
     , myTarget.[SpectatorSports_Baseball] = mySource.[SpectatorSports_Baseball]
     , myTarget.[SpectatorSports_Basketball] = mySource.[SpectatorSports_Basketball]
     , myTarget.[SpectatorSports_Hockey] = mySource.[SpectatorSports_Hockey]
     , myTarget.[SpectatorSports_Soccer] = mySource.[SpectatorSports_Soccer]
     , myTarget.[SpectatorSports_Tennis] = mySource.[SpectatorSports_Tennis]
     , myTarget.[Collectibles_SportsMemorabilia] = mySource.[Collectibles_SportsMemorabilia]
     , myTarget.[NASCAR] = mySource.[NASCAR]
     , myTarget.[SportsAndLeisure_SC] = mySource.[SportsAndLeisure_SC]
     , myTarget.[NetWorth] = mySource.[NetWorth]
     , myTarget.[HomeAssessedValue_Ranges] = mySource.[HomeAssessedValue_Ranges]
     , myTarget.[HomeSquareFootage_Actual] = mySource.[HomeSquareFootage_Actual]
     , myTarget.[HouseholdAbilitecID] = mySource.[HouseholdAbilitecID]
     , myTarget.[PersonicxDigitalCluster] = mySource.[PersonicxDigitalCluster]
     , myTarget.[PersonicxDigitalClusterCode] = mySource.[PersonicxDigitalClusterCode]
     , myTarget.[NetWorthGold] = mySource.[NetWorthGold]
     , myTarget.[RaceCode] = mySource.[RaceCode]
     , myTarget.[PersonID] = mySource.[PersonID]
     , myTarget.[Address1] = mySource.[Address1]
     , myTarget.[Address2] = mySource.[Address2]
     , myTarget.[City] = mySource.[City]
     , myTarget.[State] = mySource.[State]
     , myTarget.[PostalCode] = mySource.[PostalCode]
     , myTarget.[Country] = mySource.[Country]
     , myTarget.[HomePhone] = mySource.[HomePhone]
     , myTarget.[MobilePhone] = mySource.[MobilePhone]
     , myTarget.[AbilitecIDAppendDate] = mySource.[AbilitecIDAppendDate]
     , myTarget.[TurnkeyStandardBundleDate] = mySource.[TurnkeyStandardBundleDate]
     

WHEN NOT MATCHED BY TARGET
THEN INSERT
     ([ETL_CreatedDate]
     ,[ETL_UpdatedDate]
     ,[ETL_IsDeleted]
     ,[ETL_DeletedDate]
     ,[ETL_DeltaHashKey]
     ,[ETL_FileName]
     ,[AbilitecID]
     ,[ProspectID]
     ,[FirstName]
     ,[TicketingSystemAccountID]
     ,[LastName]
     ,[Email]
     ,[OverallMatchIndicator]
     ,[PersonicxClusterCode]
     ,[PersonicxCluster]
     ,[PrecisionLevel]
     ,[AgeInTwoYearIncrements_InputIndividual]
     ,[AgeInTwoYearIncrements_1stIndividual]
     ,[AgeInTwoYearIncrements_2ndIndividual]
     ,[Gender_InputIndividual]
     ,[Gender_1stIndividual]
     ,[Gender_2ndIndividual]
     ,[FirstName_1stIndividual]
     ,[MiddleInitial_1stIndividual]
     ,[FirstName_2ndIndividual]
     ,[MiddleInitial_2ndIndividual]
     ,[OccupationDetail_InputIndividual]
     ,[Occupation_InputIndividual]
     ,[Occupation_1stIndividual]
     ,[Occupation_2ndIndividual]
     ,[Education_InputIndividual]
     ,[Education_1stIndividual]
     ,[Education_2ndIndividual]
     ,[Males_18to24]
     ,[Females_18to24]
     ,[UnknownGender_18to24]
     ,[Males_25to34]
     ,[Females_25to34]
     ,[UnknownGender_25to34]
     ,[Males_35to44]
     ,[Females_35to44]
     ,[UnknownGender_35to44]
     ,[Males_45to54]
     ,[Females_45to54]
     ,[UnknownGender_45to54]
     ,[Males_55to64]
     ,[Females_55to64]
     ,[UnknownGender_55to64]
     ,[Males_65to74]
     ,[Females_65to74]
     ,[UnknownGender_65to74]
     ,[Males_75plus]
     ,[Females_75plus]
     ,[UnknownGender_75plus]
     ,[MaritalStatusinHousehold]
     ,[WorkingWoman]
     ,[PresenceofChildren]
     ,[NumberofAdults]
     ,[BankCardHolder]
     ,[GasDepartmentRetailCardHolder]
     ,[TravelandEntertainmentCardHolder]
     ,[CreditCardHolder_UnknownType]
     ,[PremiumCardHolder]
     ,[UpscaleCardHolder]
     ,[Income_EstimatedHousehold]
     ,[InfoBasePositiveMatchIndicator]
     ,[NumberofSources]
     ,[SuppressionMailDMA]
     ,[BusinessOwner]
     ,[BaseRecordVerificationDate]
     ,[HomeOwnerorRenter]
     ,[LengthofResidence]
     ,[HomePropertyType_Detail]
     ,[HomeYearBuilt_Actual]
     ,[DwellingType]
     ,[HomeMarketValue]
     ,[ApartmentNumber]
     ,[MailOrder_Buyer]
     ,[MailOrder_Responder]
     ,[MailOrder_Donor]
     ,[Apparel_FemaleApparel_MOBs]
     ,[Apparel_Jewelry_MOBs]
     ,[Apparel_MaleApparel_MOBs]
     ,[Apparel_PlusSizeWomensClothing_MOBs]
     ,[Apparel_TeenFashion_MOBs]
     ,[Apparel_UnknownType]
     ,[ArtandAntique_MOBs]
     ,[ArtsandCrafts_MOBs]
     ,[AutoSupplies_MOBs]
     ,[Beauty_MOBs]
     ,[Book_MOBs]
     ,[ChildrensMerchandise_MOBs]
     ,[Collectible_MOBs]
     ,[ComputerSoftware_MOBs]
     ,[Electronic_MOBs]
     ,[Equestrian_MOBs]
     ,[Food_MOBs]
     ,[GeneralGiftsandMerchandise_MOBs]
     ,[Gift_MOBs]
     ,[Health_MOBs]
     ,[HomeFurnishingandDecorating_MOBs]
     ,[Merchandise_HighTicketMerchandise_MOBs]
     ,[Merchandise_LowTicketMerchandise_MOBs]
     ,[Music_MOBs]
     ,[OutdoorGardening_MOBs]
     ,[OutdoorHuntingandFishing_MOBs]
     ,[PetSupplies_MOBs]
     ,[Sports_GolfMOBs]
     ,[Sports_MOBs]
     ,[Travel_MOBs]
     ,[VideoDVD_MOBs]
     ,[StandardRetail_MembershipWarehouse]
     ,[StandardRetail_CatalogShowroomRetailBuyers]
     ,[StandardRetail_MainStreetRetail]
     ,[StandardRetail_HighVolumeLowEndDepartmentStoreBuyers]
     ,[StandardRetail_StandardRetail]
     ,[StandardSpecialty_SportingGoods]
     ,[StandardSpecialty_SpecialtyApparel]
     ,[StandardSpecialty_Specialty]
     ,[StandardSpecialty_ComputerElectronicsBuyers]
     ,[StandardSpecialty_FurnitureBuyers]
     ,[StandardSpecialty_HomeOfficeSupplyPurchases]
     ,[StandardSpecialty_HomeImprovement]
     ,[UpscaleRetail_HighEndRetailBuyersUpscaleRetail]
     ,[UpscaleSpecialty_TravelPersonalServices]
     ,[Bank_FinancialServicesBanking]
     ,[FinanceCompany_FinancialServicesInstallCredit]
     ,[OilCompany_OilCompany]
     ,[Miscellaneous_FinancialServicesInsurance]
     ,[Miscellaneous_TVMailOrderPurchases]
     ,[Miscellaneous_Grocery]
     ,[Miscellaneous_Miscellaneous]
     ,[RetailActivity_DateofLast]
     ,[OnlinePurchasingIndicator]
     ,[Purchase_0to3Months]
     ,[Purchase_4to6Months]
     ,[Purchase_7to9Months]
     ,[Purchase_10to12Months]
     ,[Purchase_13to18Months]
     ,[Purchase_19to24Months]
     ,[Purchase_24PlusMonths]
     ,[RetailPurchases_MostFrequentCategory]
     ,[Vehicle_NewUsedIndicator_1stVehicle]
     ,[Vehicle_NewUsedIndicator_2ndVehicle]
     ,[Vehicle_DominantLifestyleIndicator]
     ,[TruckOwner]
     ,[MotorcycleOwner]
     ,[RVOwner]
     ,[Vehicle_KnownOwnedNumber]
     ,[Vehicle_NewCarBuyer]
     ,[Age00to02_Male]
     ,[Age00to02_Female]
     ,[Age00to02_UnknownGender]
     ,[Age03to05_Male]
     ,[Age03to05_Female]
     ,[Age03to05_UnknownGender]
     ,[Age06to10_Male]
     ,[Age06to10_Female]
     ,[Age06to10_UnknownGender]
     ,[Age11to15_Male]
     ,[Age11to15_Female]
     ,[Age11to15_UnknownGender]
     ,[Age16to17_Male]
     ,[Age16to17_Female]
     ,[Age16to17_UnknownGender]
     ,[DiscretionaryIncomeIndex]
     ,[Investing_Active]
     ,[SpectatorSports_AutoMotorcycleRacing]
     ,[SpectatorSports_Football]
     ,[SpectatorSports_Baseball]
     ,[SpectatorSports_Basketball]
     ,[SpectatorSports_Hockey]
     ,[SpectatorSports_Soccer]
     ,[SpectatorSports_Tennis]
     ,[Collectibles_SportsMemorabilia]
     ,[NASCAR]
     ,[SportsAndLeisure_SC]
     ,[NetWorth]
     ,[HomeAssessedValue_Ranges]
     ,[HomeSquareFootage_Actual]
     ,[HouseholdAbilitecID]
     ,[PersonicxDigitalCluster]
     ,[PersonicxDigitalClusterCode]
     ,[NetWorthGold]
     ,[RaceCode]
     ,[PersonID]
     ,[Address1]
     ,[Address2]
     ,[City]
     ,[State]
     ,[PostalCode]
     ,[Country]
     ,[HomePhone]
     ,[MobilePhone]
     ,[AbilitecIDAppendDate]
     ,[TurnkeyStandardBundleDate]
     )
VALUES
     (@RunTime		--ETL_CreatedDate
     ,@RunTime		--ETL_UpdateddDate
     ,0				--ETL_IsDeleted
     ,NULL			--ETL_DeletedDate
     ,mySource.[ETL_DeltaHashKey]
	 ,mySource.[ETL_FileName]
     ,mySource.[AbilitecID]
     ,mySource.[ProspectID]
     ,mySource.[FirstName]
     ,mySource.[TicketingSystemAccountID]
     ,mySource.[LastName]
     ,mySource.[Email]
     ,mySource.[OverallMatchIndicator]
     ,mySource.[PersonicxClusterCode]
     ,mySource.[PersonicxCluster]
     ,mySource.[PrecisionLevel]
     ,mySource.[AgeInTwoYearIncrements_InputIndividual]
     ,mySource.[AgeInTwoYearIncrements_1stIndividual]
     ,mySource.[AgeInTwoYearIncrements_2ndIndividual]
     ,mySource.[Gender_InputIndividual]
     ,mySource.[Gender_1stIndividual]
     ,mySource.[Gender_2ndIndividual]
     ,mySource.[FirstName_1stIndividual]
     ,mySource.[MiddleInitial_1stIndividual]
     ,mySource.[FirstName_2ndIndividual]
     ,mySource.[MiddleInitial_2ndIndividual]
     ,mySource.[OccupationDetail_InputIndividual]
     ,mySource.[Occupation_InputIndividual]
     ,mySource.[Occupation_1stIndividual]
     ,mySource.[Occupation_2ndIndividual]
     ,mySource.[Education_InputIndividual]
     ,mySource.[Education_1stIndividual]
     ,mySource.[Education_2ndIndividual]
     ,mySource.[Males_18to24]
     ,mySource.[Females_18to24]
     ,mySource.[UnknownGender_18to24]
     ,mySource.[Males_25to34]
     ,mySource.[Females_25to34]
     ,mySource.[UnknownGender_25to34]
     ,mySource.[Males_35to44]
     ,mySource.[Females_35to44]
     ,mySource.[UnknownGender_35to44]
     ,mySource.[Males_45to54]
     ,mySource.[Females_45to54]
     ,mySource.[UnknownGender_45to54]
     ,mySource.[Males_55to64]
     ,mySource.[Females_55to64]
     ,mySource.[UnknownGender_55to64]
     ,mySource.[Males_65to74]
     ,mySource.[Females_65to74]
     ,mySource.[UnknownGender_65to74]
     ,mySource.[Males_75plus]
     ,mySource.[Females_75plus]
     ,mySource.[UnknownGender_75plus]
     ,mySource.[MaritalStatusinHousehold]
     ,mySource.[WorkingWoman]
     ,mySource.[PresenceofChildren]
     ,mySource.[NumberofAdults]
     ,mySource.[BankCardHolder]
     ,mySource.[GasDepartmentRetailCardHolder]
     ,mySource.[TravelandEntertainmentCardHolder]
     ,mySource.[CreditCardHolder_UnknownType]
     ,mySource.[PremiumCardHolder]
     ,mySource.[UpscaleCardHolder]
     ,mySource.[Income_EstimatedHousehold]
     ,mySource.[InfoBasePositiveMatchIndicator]
     ,mySource.[NumberofSources]
     ,mySource.[SuppressionMailDMA]
     ,mySource.[BusinessOwner]
     ,mySource.[BaseRecordVerificationDate]
     ,mySource.[HomeOwnerorRenter]
     ,mySource.[LengthofResidence]
     ,mySource.[HomePropertyType_Detail]
     ,mySource.[HomeYearBuilt_Actual]
     ,mySource.[DwellingType]
     ,mySource.[HomeMarketValue]
     ,mySource.[ApartmentNumber]
     ,mySource.[MailOrder_Buyer]
     ,mySource.[MailOrder_Responder]
     ,mySource.[MailOrder_Donor]
     ,mySource.[Apparel_FemaleApparel_MOBs]
     ,mySource.[Apparel_Jewelry_MOBs]
     ,mySource.[Apparel_MaleApparel_MOBs]
     ,mySource.[Apparel_PlusSizeWomensClothing_MOBs]
     ,mySource.[Apparel_TeenFashion_MOBs]
     ,mySource.[Apparel_UnknownType]
     ,mySource.[ArtandAntique_MOBs]
     ,mySource.[ArtsandCrafts_MOBs]
     ,mySource.[AutoSupplies_MOBs]
     ,mySource.[Beauty_MOBs]
     ,mySource.[Book_MOBs]
     ,mySource.[ChildrensMerchandise_MOBs]
     ,mySource.[Collectible_MOBs]
     ,mySource.[ComputerSoftware_MOBs]
     ,mySource.[Electronic_MOBs]
     ,mySource.[Equestrian_MOBs]
     ,mySource.[Food_MOBs]
     ,mySource.[GeneralGiftsandMerchandise_MOBs]
     ,mySource.[Gift_MOBs]
     ,mySource.[Health_MOBs]
     ,mySource.[HomeFurnishingandDecorating_MOBs]
     ,mySource.[Merchandise_HighTicketMerchandise_MOBs]
     ,mySource.[Merchandise_LowTicketMerchandise_MOBs]
     ,mySource.[Music_MOBs]
     ,mySource.[OutdoorGardening_MOBs]
     ,mySource.[OutdoorHuntingandFishing_MOBs]
     ,mySource.[PetSupplies_MOBs]
     ,mySource.[Sports_GolfMOBs]
     ,mySource.[Sports_MOBs]
     ,mySource.[Travel_MOBs]
     ,mySource.[VideoDVD_MOBs]
     ,mySource.[StandardRetail_MembershipWarehouse]
     ,mySource.[StandardRetail_CatalogShowroomRetailBuyers]
     ,mySource.[StandardRetail_MainStreetRetail]
     ,mySource.[StandardRetail_HighVolumeLowEndDepartmentStoreBuyers]
     ,mySource.[StandardRetail_StandardRetail]
     ,mySource.[StandardSpecialty_SportingGoods]
     ,mySource.[StandardSpecialty_SpecialtyApparel]
     ,mySource.[StandardSpecialty_Specialty]
     ,mySource.[StandardSpecialty_ComputerElectronicsBuyers]
     ,mySource.[StandardSpecialty_FurnitureBuyers]
     ,mySource.[StandardSpecialty_HomeOfficeSupplyPurchases]
     ,mySource.[StandardSpecialty_HomeImprovement]
     ,mySource.[UpscaleRetail_HighEndRetailBuyersUpscaleRetail]
     ,mySource.[UpscaleSpecialty_TravelPersonalServices]
     ,mySource.[Bank_FinancialServicesBanking]
     ,mySource.[FinanceCompany_FinancialServicesInstallCredit]
     ,mySource.[OilCompany_OilCompany]
     ,mySource.[Miscellaneous_FinancialServicesInsurance]
     ,mySource.[Miscellaneous_TVMailOrderPurchases]
     ,mySource.[Miscellaneous_Grocery]
     ,mySource.[Miscellaneous_Miscellaneous]
     ,mySource.[RetailActivity_DateofLast]
     ,mySource.[OnlinePurchasingIndicator]
     ,mySource.[Purchase_0to3Months]
     ,mySource.[Purchase_4to6Months]
     ,mySource.[Purchase_7to9Months]
     ,mySource.[Purchase_10to12Months]
     ,mySource.[Purchase_13to18Months]
     ,mySource.[Purchase_19to24Months]
     ,mySource.[Purchase_24PlusMonths]
     ,mySource.[RetailPurchases_MostFrequentCategory]
     ,mySource.[Vehicle_NewUsedIndicator_1stVehicle]
     ,mySource.[Vehicle_NewUsedIndicator_2ndVehicle]
     ,mySource.[Vehicle_DominantLifestyleIndicator]
     ,mySource.[TruckOwner]
     ,mySource.[MotorcycleOwner]
     ,mySource.[RVOwner]
     ,mySource.[Vehicle_KnownOwnedNumber]
     ,mySource.[Vehicle_NewCarBuyer]
     ,mySource.[Age00to02_Male]
     ,mySource.[Age00to02_Female]
     ,mySource.[Age00to02_UnknownGender]
     ,mySource.[Age03to05_Male]
     ,mySource.[Age03to05_Female]
     ,mySource.[Age03to05_UnknownGender]
     ,mySource.[Age06to10_Male]
     ,mySource.[Age06to10_Female]
     ,mySource.[Age06to10_UnknownGender]
     ,mySource.[Age11to15_Male]
     ,mySource.[Age11to15_Female]
     ,mySource.[Age11to15_UnknownGender]
     ,mySource.[Age16to17_Male]
     ,mySource.[Age16to17_Female]
     ,mySource.[Age16to17_UnknownGender]
     ,mySource.[DiscretionaryIncomeIndex]
     ,mySource.[Investing_Active]
     ,mySource.[SpectatorSports_AutoMotorcycleRacing]
     ,mySource.[SpectatorSports_Football]
     ,mySource.[SpectatorSports_Baseball]
     ,mySource.[SpectatorSports_Basketball]
     ,mySource.[SpectatorSports_Hockey]
     ,mySource.[SpectatorSports_Soccer]
     ,mySource.[SpectatorSports_Tennis]
     ,mySource.[Collectibles_SportsMemorabilia]
     ,mySource.[NASCAR]
     ,mySource.[SportsAndLeisure_SC]
     ,mySource.[NetWorth]
     ,mySource.[HomeAssessedValue_Ranges]
     ,mySource.[HomeSquareFootage_Actual]
     ,mySource.[HouseholdAbilitecID]
     ,mySource.[PersonicxDigitalCluster]
     ,mySource.[PersonicxDigitalClusterCode]
     ,mySource.[NetWorthGold]
     ,mySource.[RaceCode]
     ,mySource.[PersonID]
     ,mySource.[Address1]
     ,mySource.[Address2]
     ,mySource.[City]
     ,mySource.[State]
     ,mySource.[PostalCode]
     ,mySource.[Country]
     ,mySource.[HomePhone]
     ,mySource.[MobilePhone]
     ,mySource.[AbilitecIDAppendDate]
     ,mySource.[TurnkeyStandardBundleDate]
     )
;

EXEC etl.LogEventRecordDB @Batchid, 'Info', @ProcedureName, 'Merge Load', 'Merge Statement Execution', 'Complete', @ExecutionId

DECLARE @MergeInsertRowCount INT = ISNULL((SELECT CONVERT(VARCHAR, COUNT(*)) FROM ods.Turnkey_Acxiom WHERE ETL_CreatedDate >= @RunTime AND ETL_UpdatedDate = ETL_CreatedDate),'0');	
DECLARE @MergeUpdateRowCount INT = ISNULL((SELECT CONVERT(VARCHAR, COUNT(*)) FROM ods.Turnkey_Acxiom WHERE ETL_UpdatedDate >= @RunTime AND ETL_UpdatedDate > ETL_CreatedDate),'0');	

EXEC etl.LogEventRecordDB @Batchid, 'Info', @ProcedureName, 'Merge Load', 'Merge Insert Row Count', @MergeInsertRowCount, @ExecutionId
EXEC etl.LogEventRecordDB @Batchid, 'Info', @ProcedureName, 'Merge Load', 'Merge Update Row Count', @MergeUpdateRowCount, @ExecutionId


END TRY 
BEGIN CATCH 

	DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
	DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
	DECLARE @ErrorState INT = ERROR_STATE();
			
	PRINT @ErrorMessage
	EXEC etl.LogEventRecordDB @Batchid, 'Error', @ProcedureName, 'Merge Load', 'Merge Error', @ErrorMessage, @ExecutionId
	EXEC etl.LogEventRecordDB @Batchid, 'Info', @ProcedureName, 'Merge Load', 'Procedure Processing', 'Complete', @ExecutionId

	RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState)

END CATCH

EXEC etl.LogEventRecordDB @Batchid, 'Info', @ProcedureName, 'Merge Load', 'Procedure Processing', 'Complete', @ExecutionId


END









GO
