CREATE TABLE [dbo].[Account_Backup_20151004]
(
[SSB_CRMSYSTEM_ACCT_ID] [uniqueidentifier] NOT NULL,
[SSID_Winner] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USC_Losers] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimCustID_Losers] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsBusinessAccount] [int] NOT NULL,
[FullName] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Title] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrimaryAddressType] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BillingStreet] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingCity] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingState] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingPostalCode] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingCountry] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2Type] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ShippingStreet] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShippingCity] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShippingState] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShippingPostalCode] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShippingCountry] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address3Type] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PersonOtherStreet] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonOtherCity] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonOtherState] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonOtherPostalCode] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonOtherCountry] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address4Type] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PersonMailingStreet] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonMailingCity] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonMailingState] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonMailingPostalCode] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonMailingCountry] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonHomePhone] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonMobilePhone] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fax] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecondaryEmail] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USC_Flag] [int] NULL,
[USC_SeasonTicket_Years] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Brand] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MDM_UpdatedDate] [datetime] NOT NULL,
[SFDCProcess_UpdatedDate] [datetime] NULL,
[Customer_Status] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eVenue_Email] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Donor_Status] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Donor_Type] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Donor_Level] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Internet_Profile] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eVenue_Pin] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VIP_Code] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer_Type] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Donor_ID] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAG] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer_Comments] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BusiPerson_ChgFlag] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastSFDCLoad_Error] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastSFDCLoad_AttemptDate] [datetime] NULL,
[salesforce_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SFDC_LoadDate] [datetime] NULL,
[C_PRIORITY] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Attribute] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Note] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Donor_Comments] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MembershipLevel] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
