CREATE TABLE [dbo].[SFDCLoad_Account_Prep]
(
[SSB_CRMSYSTEM_ACCT_ID__c] [uniqueidentifier] NOT NULL,
[SSB_CRMSYSTEM_SSID_Winner__c] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_USC_ID__c] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_DimCustomerID__c] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonTitle] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business_Name] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Person_RecordTypeId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business_RecordTypeId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SFDC_IsBusiness] [int] NOT NULL,
[BillingStreet] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingCity] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingState] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingPostalCode] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingCountry] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShippingStreet] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShippingCity] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShippingState] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShippingPostalCode] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShippingCountry] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonMailingStreet] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonMailingCity] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonMailingState] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonMailingPostalCode] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonMailingCountry] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonOtherStreet] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonOtherCity] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonOtherState] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonOtherPostalCode] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonOtherCountry] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonMobilePhone] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonHomePhone] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonEmail] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business_Email__c] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Secondary_Email__pc] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BusinessOnly_Email__c] [int] NULL,
[salesforce_id] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IsBusinessAccount] [int] NOT NULL,
[SSB_CRMSYSTEM_USC_Flag__c] [int] NULL,
[SSB_CRMSYSTEM_USC_Season_Ticket_Ye__c] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer_Status__c] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eVenue_Email__c] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Donor_Status__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Donor_Type__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Donor_Level__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Internet_Profile__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eVenue_Pin__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VIP_Code__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer_Type__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Donor_ID__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAG__c] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer_Comments__c] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[C_PRIORITY__C] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Attribute__C] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Note__C] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Donor_Comments__C] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Donor_Membership__c] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BusiPerson_ChgFlag] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Football_Full__c] [int] NOT NULL,
[Football_Rookie__c] [int] NOT NULL,
[Football_Partial__c] [int] NOT NULL,
[Men_s_Basketball_Full__c] [int] NOT NULL,
[Men_s_Basketball_Rookie__c] [int] NOT NULL,
[Men_s_Basketball_Partial__c] [int] NOT NULL,
[Turnkey_Discretionary_Income_Index__c] [int] NULL,
[Turnkey_Net_Worth_Gold__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Turnkey_Standard_Bundle_Date__c] [date] NULL,
[Turnkey_Age_Input_Individual__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Turnkey_Gender_Input_Individual__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Turnkey_Marital_Status__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Turnkey_Presence_of_Children__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Turnkey_Occupation_Input_Individual__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Turnkey_PersonicX_Cluster__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Turnkey_Football_Priority_Score__c] [int] NULL,
[Turnkey_Donor_Capacity_Score__c] [int] NULL,
[Turnkey_Donor_Priority_Score__c] [int] NULL,
[development__c] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
