CREATE TABLE [dbo].[Account_Errors]
(
[FirstName] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fax] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Name] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Patron_ID__c] [varchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Patron_Status__c] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer_Type__c] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer_Status__c] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingStreet] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingCity] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingState] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingPostalCode] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingCountry] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonMailingStreet] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonMailingCity] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonMailingState] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonMailingPostalCode] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonMailingCountry] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonHomePhone] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonMobilePhone] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eVenue_Email__c] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonEmail] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VIP_Code__c] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Internet_Profile__c] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer_Comments__c] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dbLastUpdated] [datetime] NULL,
[Donor_ID__c] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Export_Datetime__c] [datetime] NULL,
[DW_ContactId__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LoadDate] [datetime] NULL,
[ErrorCode] [int] NULL,
[ErrorColumn] [int] NULL,
[Id] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ErrorDescription] [nvarchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
