IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'SSBINFO\SSB IE Sec (B44D6797)')
CREATE LOGIN [SSBINFO\SSB IE Sec (B44D6797)] FROM WINDOWS
GO
CREATE USER [SSBINFO\SSB IE] FOR LOGIN [SSBINFO\SSB IE Sec (B44D6797)]
GO
